### ISSUE TITLE
ValueError: hour must be in 0..23 when using start_at='once' between 2300-2400 hrs.

### ISSUE THREAD

**Issue by gordol** [pcdinh/greenclock#4]
When starting the scheduler between the hours of 11PM and 12AM while using `start_at='once'`causes the following exception to be thrown:

```
Traceback (most recent call last):
  File "/Users/tinix/.virtualenvs/millennium-visual-management-system/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/tinix/.virtualenvs/millennium-visual-management-system/lib/python2.7/site-packages/greenclock/__init__.py", line 166, in run
    delay = task.timer.next().total_seconds()
  File "/Users/tinix/.virtualenvs/millennium-visual-management-system/lib/python2.7/site-packages/greenclock/__init__.py", line 102, in next
    return scheduled.replace(hour=now_.hour + 1) - now_
ValueError: hour must be in 0..23
<Greenlet at 0x10ec51690: <bound method Scheduler.run of <greenclock.Scheduler object at 0x10ed22d90>>(<greenclock.Task object at 0x10ed22ed0>)> failed with ValueError
```

Here is my code, very simple:

```
import greenclock
import gevent
from foo import task
scheduler = greenclock.Scheduler(logger_name='task_scheduler')
scheduler.schedule('task', greenclock.every_hour(hour=0, minute=0, second=0), task)

def run_scheduler():
    print "running scheduler"
    scheduler.run_forever(start_at='once')

gevent.spawn(run_scheduler)
```

I need to run a job at midnight.

For now, I am able to work around it via `start_at='tomorrow' and setting it to run in the first seconds of the day like this:

```
import greenclock
import gevent
from foo import task
scheduler = greenclock.Scheduler(logger_name='task_scheduler')
scheduler.schedule('task', greenclock.every_hour(hour=0, minute=0, second=5), task)

def run_scheduler():
    print "running scheduler"
    scheduler.run_forever(start_at='tomorrow')

gevent.spawn(run_scheduler)
```

Is this known and expected behavior? Seems like a bug to me...

Thanks!

**Comment by pcdinh** [comment]
Hi,

Many thanks for your bug report. I am really sorry for late report. For unknown reasons, GitHub didn't send any notification to me.

As of your report, I will check it soon.

Thanks

**Comment by gordol** [comment]
:+1:

**Comment by gordol** [comment]
@pcdinh There is also a problem with last day of month... similar error:

```
return scheduled.replace(day=now_.day + 1) - now_
ValueError: day is out of range for month
```

**Comment by gordol** [comment]
@pcdinh is this repository maintained?
